const cartTypes = {
  FETCH_CART: 'FETCH_CART',
  SET_CART: 'SET_CART',

  ADD_TO_CART: 'ADD_TO_CART',
  INCREASE_ITEM_QUANTITY: 'INCREASE_ITEM_QUANTITY',
  DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY',
  CHANGE_ITEM_QUANTITY: 'CHANGE_ITEM_QUANTITY',
  DELETE_ITEM_CART: 'DELETE_ITEM_CART',
  DELETE_CART: 'DELETE_CART',
  DELETE_CART_SUCCESS: 'DELETE_CART_SUCCESS'
};

export default cartTypes;
