const sliderTypes = {
  FETCH_SLIDER: 'FETCH_SLIDER',
  FETCH_SLIDER_SUCCESS: 'FETCH_SLIDER_SUCCESS',
  FETCH_SLIDER_PENDING: 'FETCH_SLIDER_PENDING',
  FETCH_SLIDER_FAILURE: 'FETCH_SLIDER_FAILURE'
};

export default sliderTypes;
