const categoryTypes = {
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_PENDING: 'FETCH_CATEGORIES_PENDING',
  FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',

  SET_CURRENT_CATEGORY: 'SET_CURRENT_CATEGORY',
  SET_CURRENT_CATEGORY_SUCCESS: 'SET_CURRENT_CATEGORY_SUCCESS'
};

export default categoryTypes;
