const categoryTypes =  {
  FETCH_CATEGORIES : 'FETCH_CATEGORIES',
  FETCH_CATEGORIES_SUCCESS : 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_PENDING : 'FETCH_CATEGORIES_PENDING',
  FETCH_CATEGORIES_FAILURE : 'FETCH_CATEGORIES_FAILURE',
}

export default categoryTypes;