const blogTypes = {
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',

  FETCH_POST_DETAIL: 'FETCH_POST_DETAIL',
  FETCH_POST_DETAIL_SUCCESS: 'FETCH_POST_DETAIL_SUCCESS',

  SET_MAIN_POST: 'SET_MAIN_POST',
  SET_SUB_POSTS: 'SET_SUB_POST',
  SET_LIST_POSTS: 'SET_LIST_POSTS',

  FETCH_POSTS_FIRST_LOAD: 'FETCH_POSTS_FIRST_LOAD',
  FETCH_POSTS_FIRST_LOAD_SUCCESS: 'FETCH_POSTS_FIRST_LOAD_SUCCESS',
  FETCH_POSTS_LOAD_MORE: 'FETCH_POSTS_LOAD_MORE',
  SET_LAST_VISIBLE: ' SET_LAST_VISIBLE',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR'
};

export default blogTypes;
