const blogTypes = {
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',

  FETCH_POST_DETAIL: 'FETCH_POST_DETAIL',
  FETCH_POST_DETAIL_SUCCESS: 'FETCH_POST_DETAIL_SUCCESS',

  SET_MAIN_POST: 'SET_MAIN_POST',
  SET_SUB_POSTS: 'SET_SUB_POST',
  SET_LIST_POSTS: 'SET_LIST_POSTS',
  
};

export default blogTypes;
