const productTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  FETCH_PRODUCT_TOTAL: 'FETCH_PRODUCT_TOTAL',
  SET_PRODUCT_TOTAL: 'SET_PRODUCT_TOTAL',
  FETCH_PAGINATE_PRODUCT: 'FETCH_PAGINATE_PRODUCT',
  SET_LOADING: 'SET_LOADING',
  FETCH_DETAIL_PRODUCT: 'FETCH_DETAIL_PRODUCT',
  SET_DETAIL_PRODUCT: 'SET_DETAIL_PRODUCT',
  SEARCH_PRODUCT: 'SEARCH_PRODUCT',
  FETCH_PRODUCTS_BY_CATEGORIES: 'FETCH_PRODUCTS_BY_CATEGORIES',
  FETCH_PRODUCTS_BY_CATEGORIES_SUCCESS: 'FETCH_PRODUCTS_BY_CATEGORIES_SUCCESS',
  CLEAN_PRODUCTS_CATEGORY: 'CLEAN_PRODUCTS_CATEGORY',
  FETCH_PRODUCT_BY_RANGE_PRICE: 'FETCH_PRODUCT_BY_RANGE_PRICE'
};

export default productTypes;
