const productTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  FETCH_PRODUCT_TOTAL: 'FETCH_PRODUCT_TOTAL',
  SET_PRODUCT_TOTAL: 'SET_PRODUCT_TOTAL',
  FETCH_PAGINATE_PRODUCT: 'FETCH_PAGINATE_PRODUCT',
  SET_LOADING: 'SET_LOADING',
  FETCH_DETAIL_PRODUCT: 'FETCH_DETAIL_PRODUCT',
  SET_DETAIL_PRODUCT: 'SET_DETAIL_PRODUCT',

  SEARCH_PRODUCT: 'SEARCH_PRODUCT'
};

export default productTypes;
