const orderTypes = {
  FETCH_ORDER: 'FETCH_ORDER',
  SET_ORDER: 'SET_ORDER',

  ADD_PRODUCTS_TO_ORDER: 'ADD_PRODUCTS_TO_ORDER',

  ADD_INFOR_ORDER: 'ADD_INFOR_ORDER',
  SET_PAYMENT_METHOD: 'SET_PAYMENT_METHOD',

  CHECK_OUT_SUCCESS: 'CHECK_OUT_SUCCESS',

  FETCH_ORDERS_MANAGEMENT: 'FETCH_ORDERS_MANAGEMENT',
  SET_ORDERS_MANAGEMENT: 'SET_ORDERS_MANAGEMENT',

  FETCH_ORDER_DETAIL: 'FETCH_ORDER_DETAIL',
  FETCH_ORDER_DETAIL_PENDING: 'FETCH_ORDER_DETAIL_PENDING',
  FETCH_ORDER_DETAIL_SUCCESS: 'FETCH_ORDER_DETAIL_SUCCESS',
  FETCH_ORDER_DETAIL_FAILURE: 'FETCH_ORDER_DETAIL_FAILURE'
};

export default orderTypes;
