const userTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    CLEAR_CURRENT_USER: 'CLEAR_CURRENT_USER',
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT_USER: 'LOGOUT_USER',
    SIGN_UP_USER: 'SIGN_UP_USER',
    SIGN_UP_FAILED: 'SIGN_UP_FAILED',
    SET_LOADING_BTN: 'SET_LOADING_BTN',
    SET_AUTH_ERROR: 'SET_AUTH_ERROR',
    CHECK_USER_LOGIN: 'CHECK_USER_LOGIN'
};

export default userTypes;